# Generated by Django 5.2.6 on 2025-09-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exercicio', models.CharField(max_length=150)),
                ('descricao_exercicio', models.TextField()),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('video_exercicio', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
