# Generated by Django 5.2.6 on 2025-09-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_treino_treinoexercicio_delete_pessoa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='imagem_treino',
        ),
        migrations.AddField(
            model_name='treino',
            name='url_imagem_treino',
            field=models.URLField(blank=True, null=True),
        ),
    ]
